import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { css } from '../../styled-system/css';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'Synerio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${css({ background: 'primary' })} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
